sudo: false
language: node_js
node_js:
  - '10'
  - '8'

install:
  - npm ci
  - npm i -g browserstack-runner
script: if [[ "$TRAVIS_NODE_VERSION" = "10" ]]; then npm run test:all; else npm run test; fi
after_success:
  - if [[ "$TRAVIS_NODE_VERSION" = "10" ]]; then npm run coveralls; fi
